name: flutter_profile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  # ... existing packages ...
  url_launcher: ^6.2.1


  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2

  firebase_core: ^2.32.0
  cloud_firestore: ^4.13.5
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Add this line

flutter_launcher_icons:
  android: "launcher_icon"  # Can be true, false, or custom icon name
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # <-- YOU MUST HAVE THIS SECTION -->
  assets:
    - assets/images/
    - assets/icons/
